# Generated by Django 4.2.4 on 2023-10-28 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_postdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
