# Generated by Django 4.2.4 on 2023-11-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_postdb_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.postdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb')),
            ],
        ),
    ]
