# Generated by Django 4.2.4 on 2023-11-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_likedislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
