# Generated by Django 4.2.4 on 2023-11-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_likedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
