# Generated by Django 4.2.4 on 2023-11-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_commentdb_alter_postdb_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='Username',
        ),
        migrations.AddField(
            model_name='commentdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
