# Generated by Django 4.2.4 on 2023-11-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0017_postdb_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentDB',
        ),
        migrations.DeleteModel(
            name='LikeDB',
        ),
        migrations.DeleteModel(
            name='PostDB',
        ),
    ]
