# Generated by Django 4.2.4 on 2023-11-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0018_delete_commentdb_delete_likedb_delete_postdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDB',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=400, null=True)),
                ('PImage', models.ImageField(blank=True, default=None, null=True, upload_to='PostImage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.postdb')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb')),
            ],
        ),
        migrations.CreateModel(
            name='CommentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(blank=True, max_length=100, null=True)),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.postdb')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb')),
            ],
        ),
    ]
