# Generated by Django 4.2.4 on 2023-11-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0019_postdb_likedb_commentdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedb',
            name='PostId',
        ),
        migrations.RemoveField(
            model_name='likedb',
            name='UserId',
        ),
        migrations.DeleteModel(
            name='CommentDB',
        ),
        migrations.DeleteModel(
            name='LikeDB',
        ),
    ]
