# Generated by Django 4.2.4 on 2023-11-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0023_alter_followerdb_followerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.postdb')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb')),
            ],
        ),
    ]
