# Generated by Django 3.2.10 on 2023-12-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0026_registerdb_account_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
