# Generated by Django 3.2.10 on 2023-12-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0027_registerdb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.postdb')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb')),
            ],
        ),
    ]
