# Generated by Django 3.2.10 on 2023-12-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0028_reportdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdb',
            name='ReportStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportdb',
            name='ReviewComment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
