# Generated by Django 3.2.10 on 2023-12-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0030_helpcenterdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcenterdb',
            name='UserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb'),
        ),
    ]
