# Generated by Django 3.2.10 on 2023-12-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0031_alter_helpcenterdb_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenterdb',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helpcenterdb',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
