# Generated by Django 3.2.10 on 2023-12-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0032_auto_20231226_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenterdb',
            name='MailComment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helpcenterdb',
            name='MailStatus',
            field=models.IntegerField(default=0),
        ),
    ]
